# Generated by Django 3.2.6 on 2021-11-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('sName', models.CharField(max_length=255)),
                ('plateNum', models.IntegerField()),
                ('vType', models.CharField(max_length=1000)),
            ],
        ),
    ]
